<?php /** @var \Snowdog\DevTest\Controller\VarnishesAction $this */ ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Varnishes - Cache Warmer</title>

    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/style.css" rel="stylesheet">
</head>

<body>

<?php \Snowdog\DevTest\Component\Menu::getInstance()->render() ?>

<div class="container">

    <?php if (isset($_SESSION['flash'])): ?>
        <p class="bg-info"><?= $_SESSION['flash'] ?></p>
        <?php unset($_SESSION['flash']) ?>
    <?php endif ?>

    <div>

        <div class="padded">
            <form class="form-inline" method="post" action="/varnishes">
                <div class="form-group">
                    <label for="exampleInputName2">IP</label>
                    <input type="text" name="ip" class="form-control" id="exampleInputName2"
                           placeholder="192.168.0.1">
                </div>
                <button type="submit" class="btn btn-primary">Add Varnish</button>
            </form>
        </div>

        <div class="padded">
            <h1>Varnish Assignments</h1>
        </div>

        <?php foreach ($this->getVarnishes() as $varnish): /** @var \Snowdog\DevTest\Model\Varnish $varnish */ ?>
            <?php $websiteIds = $this->getAssignedWebsiteIds($varnish) ?>
            <h2><?= $varnish->getIP() ?></h2>

            <div class="padded">
                <table class="table table-striped">
                    <tr>
                        <th>Associated</th>
                        <th>Name</th>
                        <th>Hostname</th>
                    </tr>
                    <?php foreach ($this->getWebsites() as $website): /** @var \Snowdog\DevTest\Model\Website $website */ ?>
                        <tr>
                            <td><input type="checkbox" data-varnish="<?=$varnish->getVarnishId()?>" value="<?=$website->getWebsiteId()?>" <?= in_array($website->getWebsiteId(), $websiteIds) ? 'checked="checked"' : '' ?> onclick="varnish_to_website(this)" /></td>
                            <td><?= $website->getName() ?></td>
                            <td><?= $website->getHostname() ?></td>
                        </tr>
                    <?php endforeach ?>
                </table>
            </div>

        <?php endforeach; ?>
    </div>

</div><!-- /.container -->


<script src="https://code.jquery.com/jquery-3.3.1.min.js" type="text/javascript"></script>
<script type="text/javascript">
function varnish_to_website(checkbox) {
		var checkbox = $(checkbox),
		varnish_id = checkbox.data('varnish'),
		website_id = checkbox.val(),
		is_checked = 0;

    if (checkbox.is(":checked")) {
      is_checked = 1;
    }

		$('input[type=checkbox][value='+website_id+'][data-varnish!='+varnish_id+']').prop('checked', false);

    $.ajax({
			url: 	"/varnish2website",
			type: 'POST',
			data: {
				varnish : 	varnish_id,
				website : 	website_id,
				isChecked: 	is_checked,
			},
			success: 	function(response){
				alert(response)
			},
		});
	}
</script>
</body>
</html>
